apiVersion: v2
version: latest
type: VS Code extension
name: rhamt-demo
displayName: Migration Toolkit
title: Application Migration and Modernization
description: Application Migration and Modernization
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
publisher: demo
repository: https://github.com/windup/rhamt-che-demo-dev
category: Other
firstPublicationDate: "2022-08-16"
spec:
  endpoints:
  - name: "configuration-endpoint"
    public: true
    targetPort: 61436
    attributes:
      protocol: http
  - name: "report-endpoint"
    public: true
    targetPort: 61435
    attributes:
      protocol: http
  containers:
    - image: "quay.io/windupeng/mta-vscode-extension:6.0.0.Final"
      name: rhamt-extension
      mountSources: true
      ports:
        - exposedPort: 61435
        - exposedPort: 61436
      volumes:
        - name: rhamt-vscode
          mountPath: "/home/theia/mta/redhat.mta-vscode-extension"
  extensions:
    - https://download.jboss.org/jbosstools/vscode/snapshots/mta-vscode-extension/mta-vscode-extension-0.0.99-401.vsix
